name: Preview(Develop) Deployment

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_DB_PASSWORD: ${{ secrets.DEVELOP_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_URL  }}




on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      # Get the npm cache directory.
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      # Cache dependencies.
      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install dependencies.
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install






      #Build
      - name: Build
        run: npm run ng build --configuration=development




      #- name: Test
      #  run: npm run test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  Migration:
    needs: build_and_test
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID <<< "$SUPABASE_DB_PASSWORD"
      - run: supabase db push <<< "$SUPABASE_DB_PASSWORD"


  Deploy-Preview:
    needs: Migration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      ## to be added

